baseURL: https://www.sixsidedheroes.com/
# Diable taxonmy pages (Defaults)
disableKinds:
  - taxonomy
defaultContentLanguage: en
languageCode: en-us
title: Six Sided Heroes


# changes the default pagination (Hugo >= 0.128)
pagination:
  pagerSize: 3
#changes the sumary lenght
summaryLength: 20

# Alternate Copyright company text
copyright: Digital Hammock Web Development 
copyrightURL: https://digitalhammock.com/

# this is so Hugo Will Render md To HTML
markup:
  goldmark:
    renderer:
      unsafe: true


# menu links via config file.
menu:
  main:
  - name: Digital Hammock Web Dev
    url: https://digitalhammock.com/
    weight: 100
    params:
      blank: true

# media php
mediaTypes:
  application/x-php:
    suffixes:
      - php
outputFormats:
  PHP:
    mediaType: application/x-php
    isHTML: true
    baseName: index

